
import java.util.HashMap;

class ParserTable{
    private java.util.HashMap<String,java.util.HashMap<String,String>> map;

    public ParserTable(){
    java.util.HashMap<String, String> PROGRAM = new HashMap<String,String>();PROGRAM.put("int", "STATEMENT PROGRAM");
PROGRAM.put("short", "STATEMENT PROGRAM");
PROGRAM.put("long", "STATEMENT PROGRAM");
PROGRAM.put("char", "STATEMENT PROGRAM");
PROGRAM.put("IDENTIFIER", "STATEMENT PROGRAM");
PROGRAM.put("if", "STATEMENT PROGRAM");
PROGRAM.put("while", "STATEMENT PROGRAM");
PROGRAM.put("return", "STATEMENT PROGRAM");
PROGRAM.put("{", "STATEMENT PROGRAM");
PROGRAM.put("ε", "ε");
map.put("PROGRAM", PROGRAM);
java.util.HashMap<String, String> STATEMENT = new HashMap<String,String>();STATEMENT.put("int", "DATA_TYPE TYPE_TAIL");
STATEMENT.put("short", "DATA_TYPE TYPE_TAIL");
STATEMENT.put("long", "DATA_TYPE TYPE_TAIL");
STATEMENT.put("char", "DATA_TYPE TYPE_TAIL");
STATEMENT.put("IDENTIFIER", "IDENTIFIER ID_TAIL");
STATEMENT.put("if", "IF_STATEMENT");
STATEMENT.put("while", "WHILE_LOOP");
STATEMENT.put("return", "RETURN_STMT");
STATEMENT.put("{", "BLOCK");
map.put("STATEMENT", STATEMENT);
java.util.HashMap<String, String> DATA_TYPE = new HashMap<String,String>();DATA_TYPE.put("int", "int");
DATA_TYPE.put("short", "short");
DATA_TYPE.put("long", "long");
DATA_TYPE.put("char", "char");
map.put("DATA_TYPE", DATA_TYPE);
java.util.HashMap<String, String> TYPE_TAIL = new HashMap<String,String>();TYPE_TAIL.put("IDENTIFIER", "IDENTIFIER DECL_TAIL");
TYPE_TAIL.put("[", "[ ] IDENTIFIER = new DATA_TYPE [ EXPRESSION ]");
map.put("TYPE_TAIL", TYPE_TAIL);
java.util.HashMap<String, String> DECL_TAIL = new HashMap<String,String>();DECL_TAIL.put("=", "= EXPRESSION");
DECL_TAIL.put("(", "( PARAM_LIST_OPT ) BLOCK");
map.put("DECL_TAIL", DECL_TAIL);
java.util.HashMap<String, String> ID_TAIL = new HashMap<String,String>();ID_TAIL.put("=", "= EXPRESSION");
ID_TAIL.put("(", "( ARG_LIST_OPT )");
ID_TAIL.put("[", "[ EXPRESSION ] ARR_TAIL");
map.put("ID_TAIL", ID_TAIL);
java.util.HashMap<String, String> ARR_TAIL = new HashMap<String,String>();ARR_TAIL.put("=", "= EXPRESSION");
ARR_TAIL.put("ε", "ε");
map.put("ARR_TAIL", ARR_TAIL);
java.util.HashMap<String, String> PARAM_LIST = new HashMap<String,String>();PARAM_LIST.put("int", "PARAM PARAM_LIST_TAIL");
PARAM_LIST.put("short", "PARAM PARAM_LIST_TAIL");
PARAM_LIST.put("long", "PARAM PARAM_LIST_TAIL");
PARAM_LIST.put("char", "PARAM PARAM_LIST_TAIL");
map.put("PARAM_LIST", PARAM_LIST);
java.util.HashMap<String, String> PARAM_LIST_TAIL = new HashMap<String,String>();PARAM_LIST_TAIL.put(",", ", PARAM PARAM_LIST_TAIL");
PARAM_LIST_TAIL.put("ε", "ε");
map.put("PARAM_LIST_TAIL", PARAM_LIST_TAIL);
java.util.HashMap<String, String> PARAM = new HashMap<String,String>();PARAM.put("int", "DATA_TYPE IDENTIFIER");
PARAM.put("short", "DATA_TYPE IDENTIFIER");
PARAM.put("long", "DATA_TYPE IDENTIFIER");
PARAM.put("char", "DATA_TYPE IDENTIFIER");
map.put("PARAM", PARAM);
java.util.HashMap<String, String> ARG_LIST = new HashMap<String,String>();ARG_LIST.put("IDENTIFIER", "EXPRESSION ARG_LIST_TAIL");
ARG_LIST.put("NUMBER", "EXPRESSION ARG_LIST_TAIL");
ARG_LIST.put("(", "EXPRESSION ARG_LIST_TAIL");
ARG_LIST.put("STRING", "EXPRESSION ARG_LIST_TAIL");
ARG_LIST.put("CHARACTER", "EXPRESSION ARG_LIST_TAIL");
map.put("ARG_LIST", ARG_LIST);
java.util.HashMap<String, String> ARG_LIST_TAIL = new HashMap<String,String>();ARG_LIST_TAIL.put(",", ", EXPRESSION ARG_LIST_TAIL");
ARG_LIST_TAIL.put("ε", "ε");
map.put("ARG_LIST_TAIL", ARG_LIST_TAIL);
java.util.HashMap<String, String> PARAM_LIST_OPT = new HashMap<String,String>();PARAM_LIST_OPT.put("int", "PARAM_LIST");
PARAM_LIST_OPT.put("short", "PARAM_LIST");
PARAM_LIST_OPT.put("long", "PARAM_LIST");
PARAM_LIST_OPT.put("char", "PARAM_LIST");
PARAM_LIST_OPT.put("ε", "ε");
map.put("PARAM_LIST_OPT", PARAM_LIST_OPT);
java.util.HashMap<String, String> ARG_LIST_OPT = new HashMap<String,String>();ARG_LIST_OPT.put("IDENTIFIER", "ARG_LIST");
ARG_LIST_OPT.put("NUMBER", "ARG_LIST");
ARG_LIST_OPT.put("(", "ARG_LIST");
ARG_LIST_OPT.put("STRING", "ARG_LIST");
ARG_LIST_OPT.put("CHARACTER", "ARG_LIST");
ARG_LIST_OPT.put("ε", "ε");
map.put("ARG_LIST_OPT", ARG_LIST_OPT);
java.util.HashMap<String, String> BLOCK = new HashMap<String,String>();BLOCK.put("{", "{ STATEMENT_LIST }");
map.put("BLOCK", BLOCK);
java.util.HashMap<String, String> STATEMENT_LIST = new HashMap<String,String>();STATEMENT_LIST.put("int", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("short", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("long", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("char", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("IDENTIFIER", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("if", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("while", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("return", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("{", "STATEMENT STATEMENT_LIST");
STATEMENT_LIST.put("ε", "ε");
map.put("STATEMENT_LIST", STATEMENT_LIST);
java.util.HashMap<String, String> IF_STATEMENT = new HashMap<String,String>();IF_STATEMENT.put("if", "if ( EXPRESSION ) BLOCK IF_TAIL");
map.put("IF_STATEMENT", IF_STATEMENT);
java.util.HashMap<String, String> IF_TAIL = new HashMap<String,String>();IF_TAIL.put("else", "else IF_TAIL2");
IF_TAIL.put("ε", "ε");
map.put("IF_TAIL", IF_TAIL);
java.util.HashMap<String, String> IF_TAIL2 = new HashMap<String,String>();IF_TAIL2.put("if", "if ( EXPRESSION ) BLOCK IF_TAIL");
IF_TAIL2.put("{", "BLOCK");
map.put("IF_TAIL2", IF_TAIL2);
java.util.HashMap<String, String> WHILE_LOOP = new HashMap<String,String>();WHILE_LOOP.put("while", "while ( EXPRESSION ) BLOCK");
map.put("WHILE_LOOP", WHILE_LOOP);
java.util.HashMap<String, String> RETURN_STMT = new HashMap<String,String>();RETURN_STMT.put("return", "return EXPRESSION");
map.put("RETURN_STMT", RETURN_STMT);
java.util.HashMap<String, String> EXPRESSION = new HashMap<String,String>();EXPRESSION.put("IDENTIFIER", "LOGICAL");
EXPRESSION.put("NUMBER", "LOGICAL");
EXPRESSION.put("(", "LOGICAL");
EXPRESSION.put("STRING", "LOGICAL");
EXPRESSION.put("CHARACTER", "LOGICAL");
map.put("EXPRESSION", EXPRESSION);
java.util.HashMap<String, String> LOGICAL = new HashMap<String,String>();LOGICAL.put("IDENTIFIER", "EQUALITY LOGICAL_TAIL");
LOGICAL.put("NUMBER", "EQUALITY LOGICAL_TAIL");
LOGICAL.put("(", "EQUALITY LOGICAL_TAIL");
LOGICAL.put("STRING", "EQUALITY LOGICAL_TAIL");
LOGICAL.put("CHARACTER", "EQUALITY LOGICAL_TAIL");
map.put("LOGICAL", LOGICAL);
java.util.HashMap<String, String> LOGICAL_TAIL = new HashMap<String,String>();LOGICAL_TAIL.put("&&", "&& EQUALITY LOGICAL_TAIL");
LOGICAL_TAIL.put("||", "|| EQUALITY LOGICAL_TAIL");
LOGICAL_TAIL.put("ε", "ε");
map.put("LOGICAL_TAIL", LOGICAL_TAIL);
java.util.HashMap<String, String> EQUALITY = new HashMap<String,String>();EQUALITY.put("IDENTIFIER", "COMPARISON EQUALITY_TAIL");
EQUALITY.put("NUMBER", "COMPARISON EQUALITY_TAIL");
EQUALITY.put("(", "COMPARISON EQUALITY_TAIL");
EQUALITY.put("STRING", "COMPARISON EQUALITY_TAIL");
EQUALITY.put("CHARACTER", "COMPARISON EQUALITY_TAIL");
map.put("EQUALITY", EQUALITY);
java.util.HashMap<String, String> EQUALITY_TAIL = new HashMap<String,String>();EQUALITY_TAIL.put("==", "== COMPARISON EQUALITY_TAIL");
EQUALITY_TAIL.put("!=", "!= COMPARISON EQUALITY_TAIL");
EQUALITY_TAIL.put("ε", "ε");
map.put("EQUALITY_TAIL", EQUALITY_TAIL);
java.util.HashMap<String, String> COMPARISON = new HashMap<String,String>();COMPARISON.put("IDENTIFIER", "SHIFT COMPARISON_TAIL");
COMPARISON.put("NUMBER", "SHIFT COMPARISON_TAIL");
COMPARISON.put("(", "SHIFT COMPARISON_TAIL");
COMPARISON.put("STRING", "SHIFT COMPARISON_TAIL");
COMPARISON.put("CHARACTER", "SHIFT COMPARISON_TAIL");
map.put("COMPARISON", COMPARISON);
java.util.HashMap<String, String> COMPARISON_TAIL = new HashMap<String,String>();COMPARISON_TAIL.put(">", "> SHIFT COMPARISON_TAIL");
COMPARISON_TAIL.put("<", "< SHIFT COMPARISON_TAIL");
COMPARISON_TAIL.put(">=", ">= SHIFT COMPARISON_TAIL");
COMPARISON_TAIL.put("<=", "<= SHIFT COMPARISON_TAIL");
COMPARISON_TAIL.put("ε", "ε");
map.put("COMPARISON_TAIL", COMPARISON_TAIL);
java.util.HashMap<String, String> SHIFT = new HashMap<String,String>();SHIFT.put("IDENTIFIER", "ADD SHIFT_TAIL");
SHIFT.put("NUMBER", "ADD SHIFT_TAIL");
SHIFT.put("(", "ADD SHIFT_TAIL");
SHIFT.put("STRING", "ADD SHIFT_TAIL");
SHIFT.put("CHARACTER", "ADD SHIFT_TAIL");
map.put("SHIFT", SHIFT);
java.util.HashMap<String, String> SHIFT_TAIL = new HashMap<String,String>();SHIFT_TAIL.put("<<", "<< ADD SHIFT_TAIL");
SHIFT_TAIL.put(">>", ">> ADD SHIFT_TAIL");
SHIFT_TAIL.put("ε", "ε");
map.put("SHIFT_TAIL", SHIFT_TAIL);
java.util.HashMap<String, String> ADD = new HashMap<String,String>();ADD.put("IDENTIFIER", "MUL ADD_TAIL");
ADD.put("NUMBER", "MUL ADD_TAIL");
ADD.put("(", "MUL ADD_TAIL");
ADD.put("STRING", "MUL ADD_TAIL");
ADD.put("CHARACTER", "MUL ADD_TAIL");
map.put("ADD", ADD);
java.util.HashMap<String, String> ADD_TAIL = new HashMap<String,String>();ADD_TAIL.put("+", "+ MUL ADD_TAIL");
ADD_TAIL.put("-", "- MUL ADD_TAIL");
ADD_TAIL.put("ε", "ε");
map.put("ADD_TAIL", ADD_TAIL);
java.util.HashMap<String, String> MUL = new HashMap<String,String>();MUL.put("IDENTIFIER", "MOD MUL_TAIL");
MUL.put("NUMBER", "MOD MUL_TAIL");
MUL.put("(", "MOD MUL_TAIL");
MUL.put("STRING", "MOD MUL_TAIL");
MUL.put("CHARACTER", "MOD MUL_TAIL");
map.put("MUL", MUL);
java.util.HashMap<String, String> MUL_TAIL = new HashMap<String,String>();MUL_TAIL.put("*", "* MOD MUL_TAIL");
MUL_TAIL.put("/", "/ MOD MUL_TAIL");
MUL_TAIL.put("ε", "ε");
map.put("MUL_TAIL", MUL_TAIL);
java.util.HashMap<String, String> MOD = new HashMap<String,String>();MOD.put("IDENTIFIER", "PRIMARY MOD_TAIL");
MOD.put("NUMBER", "PRIMARY MOD_TAIL");
MOD.put("(", "PRIMARY MOD_TAIL");
MOD.put("STRING", "PRIMARY MOD_TAIL");
MOD.put("CHARACTER", "PRIMARY MOD_TAIL");
map.put("MOD", MOD);
java.util.HashMap<String, String> MOD_TAIL = new HashMap<String,String>();MOD_TAIL.put("%", "% PRIMARY MOD_TAIL");
MOD_TAIL.put("ε", "ε");
map.put("MOD_TAIL", MOD_TAIL);
java.util.HashMap<String, String> PRIMARY = new HashMap<String,String>();PRIMARY.put("IDENTIFIER", "IDENTIFIER PRIMARY_TAIL");
PRIMARY.put("NUMBER", "NUMBER");
PRIMARY.put("(", "( EXPRESSION )");
PRIMARY.put("STRING", "STRING");
PRIMARY.put("CHARACTER", "CHARACTER");
map.put("PRIMARY", PRIMARY);
java.util.HashMap<String, String> PRIMARY_TAIL = new HashMap<String,String>();PRIMARY_TAIL.put("(", "( ARG_LIST_OPT )");
PRIMARY_TAIL.put("[", "[ EXPRESSION ]");
PRIMARY_TAIL.put("ε", "ε");
map.put("PRIMARY_TAIL", PRIMARY_TAIL);


    }

    public String get(String nonTerminal,String Terminal){
        return map.get(Terminal).get(nonTerminal);
    }

}    
